language: python
python:
  - "3.4"
install:
  - "pip3 install -r requirements.txt"
  - "pip3 install coveralls"
notifications:
  email:
    on_success: never
    on_failure: change
script:
  nosetests --with-coverage --cover-package=setupam
after_success:
  coveralls